divcraft/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('message.urls')),
]


urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='user'

urlpatterns = [
    #path('associate/<str:name>/<str:tag>',views.associateTag_view,name='associate'),
    path('detail/',views.userDetail_view,name='detail'),
	path('choice/',views.choice_view,name='choice'),
    path('registration/', views.registration_view,name='registration'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('activate/<str:activate_pass>/',views.activate,name="activate"),
    path('newpass/<str:activate_pass>/<str:user>/',views.newpass_view, name="newpass"),
    path('forgotconfirm/',views.forgotConfirm_view,name='forgotconfirm'),
    #path('aboutus/',views.aboutUs_view,name="aboutus"),
    #path('follow/<str:follower>/<str:followed>/',views.follow_view,name='follow'),
    #path('unfollow/<str:unfollower>/<str:unfollowed>/',views.unfollow_view,name='unfollow'),
]

user/models.py
import uuid
from django.db import models
from multiselectfield import MultiSelectField
from django_countries.fields import CountryField
from django_mysql.models import ListCharField

sex_choices =(('Male','Male'),('Female','Female'),('Other','Other'),('Rather not ask','Rather not ask'))
profile_choices = (('Male','<img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png">'),('Female','Female'),('Other','Other'),('Rather not ask','Rather not ask'))


# Create your models here.
class user(models.Model):

	#userid = models.AutoField(default=0,primary_key=True)
	active = models.BooleanField(default=False)
	activate_pass = models.CharField(default=uuid.uuid1(),max_length=100)
	username = models.CharField(max_length=25)
	usernameid = models.CharField(default='',max_length=25,unique=True,blank=False,primary_key=True)
	#profile_pic = models.CharField(max_length=100,choices=profile_choices)
	#asssociaters
	bio = models.CharField(default='',max_length=200)
	message = models.CharField(default='',max_length=2000)

	blockList = ListCharField(default='',base_field=models.CharField(default='',max_length=25),size=10000,max_length=(100000*25))

	DOB = models.DateField(blank=False)
	sex = models.CharField(max_length=25,choices=sex_choices)
	country = CountryField(default='',blank=True)
	
	emailId = models.EmailField(max_length=64,unique=True,blank=False)


def __str__(self):
	return (self.username)

user/forms.py
from django import forms
from . import models


class CreateUserDetail(forms.ModelForm):
	class Meta:
		model = models.user
		fields = ['username','usernameid','bio','message','DOB','sex','country','emailId']


class EditUser(forms.ModelForm):
	class Meta:
		model = models.user
		fields = ['bio','message','sex','DOB']

user/views.py
from django.shortcuts import render,redirect
from . import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from .models import user as user_detail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User as userprim
from django.core.mail import EmailMessage

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
import uuid

# feed back page
def aboutUs_view(request):

	return render(request,'aboutUs.html')



# forgot password confirmation
def forgotConfirm_view(request):
	if(request.POST):
		try:
			userDetail = user_detail.objects.get(emailId=request.POST['emailId'])
		except:
			return HttpResponse("No user registerd with given address")


		userDetail = user_detail.objects.get(emailId=request.POST['emailId'])
		# email does not exisr logic

		userDetail.activate_pass = uuid.uuid1()
		userDetail.save()

		current_site = get_current_site(request)

		mail_subject = "Forgot password"

		message = render_to_string('forgot.html',{'user':userDetail,'domain':current_site.domain,'activate_pass':userDetail.activate_pass,'user':userDetail.usernameid})

		send_mail(mail_subject,message,'divcraft45@gmail.com',[userDetail.emailId],fail_silently=False)



		return HttpResponse(" Check your Email for reset link .")


	else:
		return render(request,'forgot_form.html')


# new password creator
def newpass_view(request,activate_pass,user):
	try:
		user = userprim.objects.get(username=user)
	except:
		return redirect('message:warning',messageheader="User confirmation failled.",message="You did something wrong. Generate the link again .")

	userDetail = user_detail.objects.get(pk=user.username)

	if(userDetail.activate_pass != activate_pass):
		return redirect('message:warning',messageheader="User confirmation failled.",message="You did something wrong. Generate the link again .")


	print(user.password)
	if (request.POST):

		user.password = make_password(request.POST['password'],salt=None,hasher='default')
		userDetail.activate_pass = " "
		user.save()

		return HttpResponse("password reset successfull")
	else:

		form = PasswordChangeForm(user=user)
		return render(request,'newpass.html',{'activate_pass':activate_pass,'form':form,'user':user.username})





# create user details
def userDetail_view(request):
	userprim = request.user
	print(userprim)
	user = request.user.username
	if request.method == 'POST':
		detail_form = forms.CreateUserDetail(request.POST,request.FILES)
		if detail_form.is_valid():
			instance = detail_form.save()
			print("$$ user active status $$")
			current_site = get_current_site(request)
			mail_subject = "Acivate email."
			userDetail = user_detail.objects.get(pk=user)

			message = render_to_string('acc_active_email.html', {'user': userprim, 'domain': current_site.domain,'activate_pass':userDetail.activate_pass,})

			send_mail(mail_subject , message ,'divcraft45@gmail.com',[request.POST['emailId']] , fail_silently=False ,)

			return redirect('message:home')
	else:
		detail_form = forms.CreateUserDetail()
	return render(request,'userDetail.html',{'form':detail_form,'user':user})


def activate(request, activate_pass):
	user = request.user
	username = user.username
	userDetail = user_detail.objects.get(pk=username)

	if (userDetail.activate_pass == activate_pass):
		userDetail.active = True
		userDetail.activate_pass = ""
		userDetail.save()
		return HttpResponse("Validated")
	else:
		return HttpResponse("In Valid get new validation link")
	#try:
	#	uid = force_text(urlsafe_base64_decode(uidb64))
	#	user = user_detail.objects.get(pk=username)
	#except(TypeError, ValueError, OverflowError, User.DoesNotExist):
	#	user = None
	#if user is not None and account_activation_token.check_token(user, token):
	#	user.active = True
	#	user.save()
	#	login(request, user)
	#	return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
	#else:
	#	return HttpResponse('Activation link is invalid!')

#  login a user
def login_view(request):
	if request.method == 'POST' :
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request,user)

			return redirect('message:home')

			# redirect to source page 
			# may be not needed if kept at on first place
			# or design a closed app

	else:
		form = AuthenticationForm()
	return render(request,'login.html',{'form':form})

# logout a user
def logout_view(request):
	logout(request)
	return redirect('message:message')

# shows the choice page
def choice_view(request):
	return render(request,'choice.html')

# Create your views here.
def registration_view(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request,user)
			return redirect('message:home')
			# lead to extra detail addition or verification
	else:
		form = UserCreationForm()

	return render(request,'regist.html',{'form':form})

user/templates/aboutUs.html
<!DOCTYPE html>
<html>
<head>
	<title>THE CRITIC'S PAGE</title>
	<!-- BOOTSTRAP -->

	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	{%load static%}
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
	{%load static%}



</head>
<body style="background-image: url(/media/LOGO.jpg);background-repeat: no-repeat; background-attachment: fixed; background-position: center; background-size: cover;" class="bg-dark">

	<div class="container-fluid">
		<div class="row">
		
			<div class="col-sm-2"></div><!-- Space -->


			<div class="col-sm-8" style="margin-top: 15%">
				<div class=" ">
					<h1 class="text-head">ABOUT US:</h1>
					<p class="text-para">
						A try to make it better this time.
					</p>
					{% block main%}


					{% endblock %}		
				</div>

			</div>

			<div class="col-sm-2"></div><!-- Space -->
		</div>
	</div>

	


</body>
</html>

user/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' activate_pass=activate_pass %}
{% endautoescape %}

user/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>THE CRITIC'S PAGE</title>
	<!-- BOOTSTRAP -->

	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	{%load static%}
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
	{%load static%}



</head>
<body>

	<div class="container-fluid">
		<div class="row">
		
			<div class="col-sm-2"></div><!-- Space -->


			<div class="col-sm-8" style="margin-top: 15%">
				<div class="jumbotron ">
					{% block main%}


					{% endblock %}		
				</div>

			</div>

			<div class="col-sm-2"></div><!-- Space -->
		</div>
	</div>

	


</body>
</html>

user/templates/choice.html
{% extends 'base.html' %}

{% block main%}
	<div class="row">
		<div class="col-sm-6">
			<center>
				<a class="choice" href="{% url 'user:registration' %}">Registration</a>
			</center>
		</div>
		
		<div class="col-sm-6">
			<center>
			<a class="choice" href="{% url 'user:login' %}">Login</a>	
			</center>
		</div>
	</div>
	<br>
{% endblock %}

user/templates/forgot.html
{% autoescape off %}
Hi {{ user }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:newpass' activate_pass=activate_pass user=user %}
{% endautoescape %}

user/templates/forgot_form.html
{% extends 'base.html' %}

	{% block main %}

		<form action="{% url 'user:forgotconfirm' %}" method="POST">
			{%csrf_token%}
			Email-Id:<br>
			<input type="email" id='id_emailId' name="emailId"><br>
			<input class="btn btn-primary" type="submit" name="">

		</form>

	{% endblock %}

user/templates/login.html
{% extends 'base.html' %}

	{% block main%}


	<form action="{% url 'user:login' %}" method="POST">
		{% csrf_token %}
		{{ form }}
		<a href="{% url 'user:forgotconfirm' %}" >Forgot Password</a>
		<br>
			
		<input class="btn btn-primary" type="submit" name="" value="submit">
	</form>

	{% endblock %}

user/templates/newpass.html
{% extends 'base.html' %}
	{% block main %}
		
		<form method="POST"action="{% url 'user:newpass' activate_pass user%}"> 
			{% csrf_token %}
			Password :<br>
			<input type="password" id="id_password" name="password"><br>
			Confirm Password :<br>
			<input type="password" id="id_password" name=""><br>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>

	{% endblock %}

user/templates/regist.html
{% extends 'base.html' %}


{% block main%}
	<form action="{% url 'user:registration' %}" method="POST">
		{% csrf_token %}
		{{form}}
		
		<input class="btn btn-primary" type="submit" name="submit" value="submit">
	</form>

{% endblock %}

user/templates/userDetail.html
{% extends 'base.html' %}



{% block main %}

	<form action="{% url 'user:detail' %}" method="POST" enctype="multipart/form-data">
		<a class="btn float-right" href="{% url 'user:logout' %}">LOGOUT</a>
		{% csrf_token %}
		{{form}}
		<input class="btn btn-primary" type="Submit" name="">
	</form>
	<script type="text/javascript">
		document.getElementById('id_usernameid').value = "{{user}}";
		document.getElementById('id_usernameid').readOnly = true;

	</script>

{% endblock %}