divcraft/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('message.urls')),
]


urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

message/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = 'message'

urlpatterns = [
    path('home/',views.home_view,name='home'),
    path('create/<str:user_2>/',views.create_view,name='create'),# safe as it call user one authenticity and only connects to other
    path('message/', views.message_view, name = 'message'),
    path('detail/<str:messageid>/',views.messagedetail_view,name='detail'),  # safe give the conversation
    path('chat/<str:messageid>',views.chat_view, name="chat"), # safe redirect to detail after adding message
    path('',views.animation_view,name="animation"),
    path('warning/<str:messageheader>/<str:message>/',views.warning_view,name="warning"),
    path('messageBlock/<str:messageid>/',views.messageBlock_view,name="messageBlock"),#safe render convo in message detail
    path('profile/',views.profile_view,name="profile"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='user'

urlpatterns = [
    #path('associate/<str:name>/<str:tag>',views.associateTag_view,name='associate'),
    path('detail/',views.userDetail_view,name='detail'),
	path('choice/',views.choice_view,name='choice'),
    path('registration/', views.registration_view,name='registration'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('activate/<str:activate_pass>/',views.activate,name="activate"),
    path('newpass/<str:activate_pass>/<str:user>/',views.newpass_view, name="newpass"),
    path('forgotconfirm/',views.forgotConfirm_view,name='forgotconfirm'),
    #path('aboutus/',views.aboutUs_view,name="aboutus"),
    #path('follow/<str:follower>/<str:followed>/',views.follow_view,name='follow'),
    #path('unfollow/<str:unfollower>/<str:unfollowed>/',views.unfollow_view,name='unfollow'),
]

message/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django_countries.fields import CountryField




# Create your models here.
class Message(models.Model):
	
	# id
	messageid = models.AutoField(max_length=15,primary_key=True,unique=True)
	user1 = models.CharField(max_length=25)
	user2 = models.CharField(max_length=25)


	
	# distinction Fields
	date = models.DateTimeField(auto_now_add=True)
	messageBlock = models.TextField()
	like = models.BooleanField(default=False)
	
	
	#content


def __str__(self):
	return self.feedId

def html(self):
	return self.title

message/forms.py
from django import forms
from . import models

class CreateMessage(forms.ModelForm):
	class Meta:
		model = models.Message
		fields = ['user1','user2']

message/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . import forms
from user import forms as user_forms
from .models import Message as messagemodel
from user.models import user as usermodel
from django.contrib.auth.decorators import login_required


# chat creater
@login_required(login_url="/user/choice")
def profile_view(request):
	
	user = request.user
	name = str(user.username)
	if request.method == 'POST' :
		print("$%32423424312")
		userdetail = usermodel.objects.get(pk=name)
		form = user_forms.EditUser(data=request.POST,instance=userdetail)
		if form.is_valid():
			form.save()

			return redirect('message:profile')

	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):

		userdetail = usermodel.objects.get(pk=name) 
		
		form = user_forms.EditUser(initial={'bio':userdetail.bio,'message':userdetail.message,'emailId':userdetail.emailId,'sex':userdetail.sex,'DOB':userdetail.DOB})

		return render(request,'profile.html',{'user':userdetail,'form':form})
		

	#	

	else:
		return redirect('user:detail')












# chat creater
@login_required(login_url="/user/choice")
def messageBlock_view(request,messageid):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):


		
		messagedetail = messagemodel.objects.get(messageid=messageid)
		if not(messagedetail.user1 == name or messagedetail.user2 == name):
			return redirect('message:warning',messageheader="warning",message="A illegal request was tried.")
		
		return render(request,'messageBlock.html',{ 'messagedetail':messagedetail })
		

	#	

	else:
		return redirect('user:detail')






def warning_view(request,messageheader,message):

	return render(request,'warning.html',{'messageheader':messageheader,'message':message})




@login_required(login_url="/user/choice")
def validator(request):
	user = request.user.username
	print(user)
	try:
		user = usermodel.objects.get(pk=user)
	except:
		return True
	else:
		return user.active




# chat creater
@login_required(login_url="/user/choice")
def animation_view(request):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):

		return render(request,'animation.html')
		

	#	

	else:
		return redirect('user:detail')

# chat creater
@login_required(login_url="/user/choice")
def chat_view(request,messageid):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):

		message = messagemodel.objects.get(pk=messageid)
		if not(message.user1 == name or message.user2 == name):
			return redirect('message:warning',messageheader="warning",message="A illegal request was tried.")


		message.messageBlock += "<h6>"+str(user)+"</h6>"+"<p >"+str(request.POST['chat'] )+"</p>"

		message.save()

		return redirect('message:detail',messageid)

		
		


	#	for user in 

	#	

	#	

	else:
		return redirect('user:detail')

# create message 
@login_required(login_url="/user/choice")
def create_view(request,user_2):
	user = request.user
	name = user.username
	messagemodel(user1=user,user2=user_2).save()

	print(messagemodel.objects.all())


	return redirect('message:message')



#message content

#
#
#$$$$$$$$$$$$$$$$$$$$$               DELTELTE                    $$$$$$$$$$$$$$$$$$$$$$$$$$
##
#
@login_required(login_url="/user/choice")
def messagecontent_view(request):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):
		
		userdetail = usermodel.objects.get(pk=name)



		blocks =[]

		#for blocked in user.blockList:
		#	blocks.append(usermodel.objects.get(pk=blocked))


		messages = []

		
		message = messagemodel.objects.get(user1__exact=name)
		messages.append(message)
		message = messagemodel.objects.get(user2__exact=name)
		messages.append(message)


		print(user)

		return render(request,'messageContent.html',{'blocks':blocks,'messages':messages,'user_main':user})

	#	for user in 

	#	

	#	

	else:

		return redirect('user:detail')

# home page
@login_required(login_url="/user/choice")
def home_view(request):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):
		


		return render(request,'home.html')

	elif(not validator(request)):

		return redirect('message:warning',messageheader="User confirmation failled.",message="Open registered email inbox and confirm your id with specified URL.")

	#	for user in 

	#	

	#	

	else:

		return redirect('user:detail')

# main message page
@login_required(login_url="/user/choice")
def message_view(request):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):
		
		userdetail = usermodel.objects.get(pk=name)


		users = list(usermodel.objects.order_by('?'))
		users.remove(userdetail)

		blocks =[]

		#for blocked in user.blockList:
		#	blocks.append(usermodel.objects.get(pk=blocked))
		messages = []
	
		messagelist = messagemodel.objects.filter(user1=userdetail.usernameid)
		for message in messagelist:
			messages.append(message)
	
		messagelist = messagemodel.objects.filter(user2=userdetail.usernameid)
		for message in messagelist:
			messages.append(message)
			
		messageusers = []

		for message in messages:
			messageusers.append(message.user1)
			messageusers.append(message.user2)
		print(messageusers)

		userlist = users.copy()

		for user in users:
			print( user.usernameid)
			if(user.usernameid in messageusers):
				userlist.remove(user)
		
		user = request.user
		print(user)
		return render(request,'messageMain.html',{'users':userlist,'blocks':blocks,'messages':messages,'user_main':user})

	else:

		return redirect('user:detail')
	if False:
		user = request.user()
		subsetSize = 100

		usertags = 0 # get tags on user

		feedlist = feedLister(usertags)
		feedlist = feedSequencer(feedlist)
		feed = feedCreator(feedlist,subsetSize)

	feed = feedmodel.objects.all().order_by('feedId')

	return render(request,'render.html',{'feedList':feed})

# view message
@login_required(login_url="/user/choice")
def messagedetail_view(request,messageid):
	user = request.user
	name = str(user.username)
	try :
		userdetail = usermodel.objects.get(pk=name)
	except :
		userdetail = False
	else:
		userdetail = True
	
	if( userdetail and validator(request) ):
		userdetail = usermodel.objects.get(pk=name)
		users = list(usermodel.objects.order_by('?'))
		users.remove(userdetail)
		blocks =[]

		#for blocked in user.blockList:
		#	blocks.append(usermodel.objects.get(pk=blocked))
		messages = []
	
		messagelist = messagemodel.objects.filter(user1=userdetail.usernameid)
		for message in messagelist:
			messages.append(message)
			print(message)
		messagelist = messagemodel.objects.filter(user2=userdetail.usernameid)
		for message in messagelist:
			messages.append(message)
			print(message)

		print (messages)



	
		messagedetail = messagemodel.objects.get(messageid=messageid)
		if not(messagedetail.user1 == name or messagedetail.user2 == name):
			return redirect('message:warning',messageheader="warning",message="A illegal request was tried.")




		print(messagedetail.user1)

		return render(request,'messageContent.html',{'messages':messages,'blocks':blocks,'messagedetail':messagedetail,'user_main':user,'messageid':messageid})

	#	for user in 

	#	

	#	

	else:

		return redirect('user:detail')

message/templates/animation.html
<!DOCTYPE html>
<html>
<head>
		<title>DIVCRAFT</title>
		<!-- Bootstrap -->
		<style type="text/css"></style>



		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
		{%load static%}
		<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
		{%load static%}

		<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
     	 rel="stylesheet">

     	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
		


		<style>
		@import url('https://fonts.googleapis.com/css?family=Pacifico|Righteous&display=swap');	
		</style>
		<style>@import url('https://fonts.googleapis.com/css?family=Source+Code+Pro&display=swap');
</style>
</style>

</head>
<body class="bg-dark">
		<div class="bg-dark">
			<center>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<h1 style="font-family: 'Source Code Pro', monospace;" id="logo" class="logo-animate logo logo-page"></h1>
				<p style="font-family: 'Source Code Pro'," id="subline" class="subline">presents
				</p>
				<br>
				<br>
				<br>
				<br>
				<br>
			</center>
		</div>
	<script type="text/javascript">
		
		var i = 0;
		var str = "<div>__craft";
		var st = "";
		var time = setInterval(type, 250);



		function type(){
			if(str[i] ==undefined){
				clearTimeout(time);
				window.open("{% url 'message:home' %}","_self");
				return (0);
			}
			else if(str[i] == '<'){
				st += "&lt";
			}
			else if(str[i] == '>'){
				st += "&gt";
			}
			else{
				st += str[i];

			}
			console.log(st);
			document.getElementById('logo').innerHTML = st;
			i+=1;
		}

		function animateCSS(element, animationName, callback) {
		    const node = document.querySelector(element)
		    node.classList.add('animated', animationName)

		    function handleAnimationEnd() {
		        node.classList.remove('animated', animationName)
		        node.removeEventListener('animationend', handleAnimationEnd)

		        if (typeof callback === 'function') callback()
		    }

		    node.addEventListener('animationend', handleAnimationEnd)
		}

	</script>




</body>
</html>

message/templates/create.html
{% extends 'feedBase.html' %}

	{% block main%}
		<div class="col-sm-6">
			<form action="{% url 'message:create' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{form}}
				<div>
					<input class="float-right btn btn-success" type="submit" name="" value="SUBMIT">
				</div>
				
			</form>
		</div>
		

	{% endblock %}

message/templates/home.html
{% extends 'homeBase.html' %}
	

	{% block main%}

		<!-- 2nd block -->
		<div class="container-fluid">
			
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-7 connect-info">
						<h3 class="info">Somedays its the most logical thing in life.<br>Somedays its the biggest mistake I ever did.<br>
						Finally it is here.</h1>
						<p class="info"> Desiring to make it logical this time.<br>We present to you DIV__CRAFT <br>Just connect and find someone who is wishing for someone at the very moment</p>
						<h5 class="info">May god bless!</h5>
				</div>
				<div class="col-sm-3">
						<button type="" onclick="window.open({% url 'message:message' %},'_self')" class="float-right btn btn-primary connect bg-dark info">Connect</button>



				</div>
				<div class="col-sm-1"></div>

			</div>
		</div>
	{% endblock%}

message/templates/homeBase.html
<!DOCTYPE html>
<html>
<head>
	<title>DIVCRAFT</title>
	<!-- Bootstrap -->
	<style type="text/css"></style>



	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	{%load static%}
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
	{%load static%}


	<style>
	@import url('https://fonts.googleapis.com/css?family=Pacifico|Righteous&display=swap');	
	</style>

</head>
<body>
	<div class="">
		<nav class="float-right navbar navbar-expand-sm bg-dark">
				<ul class="navbar-nav ">
				
				<!--<li class="nav-item">
					<a class="nav-link text-light" href="">HOME</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-light" href="">ABOUT US</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-light" href="">FEEDBACK</a>
				</li>-->

				<li class="nav-item">
				    <a class="nav-link text-light" href="{% url 'user:logout' %}">LOGOUT</a>
				</li>
				<li class="nav-item">
				  	<a class="nav-link text-light" href="{% url 'message:profile' %}">ACCOUNT</a>
				</li>

			</ul>			
		</nav>

		<div class="bg-dark">
			<center>
				<h1 class="logo logo-page">DIV_ _CRAFT</h1>
			</center>
		</div>
		<br><br>
	{% block main%}

	{% endblock %}



	</div>






</body>
</html>

message/templates/messageBase.html
<!DOCTYPE html>
<html style="height: 100%">
	<head>
		<title>DIVCRAFT</title>
		<!-- Bootstrap -->
		<style type="text/css"></style>



		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
		{%load static%}
		<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
		{%load static%}

		<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
     	 rel="stylesheet">

		<style>
		@import url('https://fonts.googleapis.com/css?family=Pacifico|Righteous&display=swap');	
		</style>
		{% block head %}

		{% endblock %}





	</head>
	<body style="height: 100%">

		<a style="padding: 10px;" class="float-right btn" href="{% url 'user:logout' %}">LOGOUT </a>




		<div class="" style="height: 100%">
			<div class="row" style="height: 100%" >
				<div class="col-sm-4 bg-dark" style="height: 100%;">
					{% block request %}

					{% endblock %}
				</div>
				<div class="col-sm-8" style="height: 100%;">
					{% block choice%}

					{% endblock %}
				</div>
			</div>
		</div>
		
	</body>
</html>

message/templates/messageBlock.html
				<head>
		<title>DIVCRAFT</title>
		<!-- Bootstrap -->
		<style type="text/css"></style>



		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
		{%load static%}
		<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
		{%load static%}
		<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
		{%load static%}

		<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
     	 rel="stylesheet">

		<style>
		@import url('https://fonts.googleapis.com/css?family=Pacifico|Righteous&display=swap');	
		</style>
		{% block head %}

		{% endblock %}


		<meta http-equiv="refresh" content="5" />



	</head>





			<div id="chatblock"  style="overflow:scroll; height:500px;">


				{{messagedetail.messageBlock | safe }}


				<script type="text/javascript">
					document.getElementById('chatblock').scrollTo(0,	document.getElementById('chatblock').scrollHeight);
				</script>
			</div

message/templates/messageContent.html
{% extends 'messageBase.html' %}

{% block head %}

{% endblock %}




	{% block request %}
	<br>
	<a href="{% url 'message:message' %}"><i class="material-icons">arrow_back_ios</i></a>
	<br>
	<br>
		{% for message in messages %}
			<div class="card">
				<div class="card-header">
					
				</div>

				<div class="card-footer">
					{% if user_main.username == message.user1 %}
						{{message.user2}}
					{% else %}
						{{message.user1}}
					{% endif %}
					<br>
					<a href="{% url 'message:detail' message.messageid %}">Chat</a>
				</div>
			</div>
			<br>
			<br>

		{% endfor %}

	{% endblock %}

	{% block choice%}
	<br>
	<br>
		<div class="card">
			<div class="card-header">
				{{messagedetail.user1}}
				{{messagedetail.user2}}
			</div>
				

			<iframe id="iframe1" height="505px" class="card-body card" style="overflow:hidden; margin: 0px; padding: 0px;" src="{% url 'message:messageBlock' messageid %}" >
				


			</iframe>




			


			<div class="card-footer">
				<form action="{% url 'message:chat' messagedetail.messageid %}" method="POST">
					{% csrf_token %}
					<div class="container-fluid">
						<div class="row">
							<div class="col-sm-8">
								<input class="form-control" type="text" name="chat" style="display: inline;" required autofocus>
							</div>
							<div class="col-sm-4">
								<button type="submit" class="btn btn-primary bg-dark"> >>> </button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>

	{% endblock %}

message/templates/messageMain.html
{% extends 'messageBase.html' %}

	{% block request %}
	<br>
	<a href="{% url 'message:home' %}"><i class="material-icons">arrow_back_ios</i></a>
	<br>
	<br>
		{% for message in messages %}
			<div class="card">
				<div class="card-header">
					
				</div>

				<div class="card-footer">
					{% if user_main.username == message.user1 %}
						{{message.user2}}
					{% else %}
						{{message.user1}}
					{% endif %}
					<br>
					<a href="{% url 'message:detail' message.messageid %}">Chat</a>
				</div>
			</div>
			<br>
			<br>

		{% endfor %}

	{% endblock %}

	{% block choice%}
	<br>                                                        
	<br>
		{% for user in users %}
			<div class="card">
				<div class="card-header">
					{{user.usernameid}}
				</div>
					
				<div class="card-body">
					{{user.bio}}
					{{user.messsage}}
				</div>
				
				<div class="card-footer">
					<a href="{% url 'message:create' user.usernameid %}">Connect</a>
				</div>
			</div>
			<br>
		{% endfor %}

	{% endblock %}

message/templates/profile.html
{% extends 'messageBase.html' %}



{% block request %}
	<br>
	<a href="{% url 'message:home' %}"><i class="material-icons">arrow_back_ios</i></a>
	<br>
	<br>
	<div class="card">
		<div class="card-header">
			<h4 class="text-head text-dark">{{user.username}}</h4>
		</div>
		<div class="card-body">
			<p class="text-para text-secondary">BIO:<br>{{user.bio}}</p>
			<p class="text-para text-secondary">MESSAGE:<br>{{user.message}}</p>
		</div>
		<div class="card-footer">
			<p class="text-para text-info">{{user.emailId}}</p>
		</div>
	</div>

{% endblock %}

{% block choice %}
	<div style="margin-top: 200px;">
		<div class="card">
			<div class="card-body">
				<form action="{% url 'message:profile' %}" method="POST">
					{%csrf_token%}
					{{form}}
					<br>
					<button type="submit" class="float-right btn btn-primary">SUBMIT</button>
				</form>
			</div>
		</div>
	</div>
	


{% endblock %}

message/templates/render.html
{% extends 'feedBase.html' %}


				{% block main %}
				<h1>Messages</h1>
					{% for message in messages%}
						{{message.user1}}
						{{message.user2}}
					{% endfor%}
				{% endblock %}	


				{% block bList %}
				<h1>BLocked</h1>
					{% for block in blocks %}
						{{block.username}}
						{{block.bio}}
						{{block.message}}
						<br>
						$$$$
					{% endfor %}


				{% endblock %}

				{% block choose %}
					<h1> Choose</h1>
					{% for user in users %}
						{{user.username}}
						{{user.bio}}
						{{user.message}}
						$$$$
						<br>
					{% endfor %}

				{% endblock %}

message/templates/warning.html
{% extends 'warning_base.html' %}
	{% block main%}
		<h2>{{messageheader}}</h2>
		<br>
		<p>{{message}}</p>
		<a class="float-right btn btn-secondary" href="{% url 'message:animation' %}">RETRY</a>
	{% endblock %}

message/templates/warning_base.html
<!DOCTYPE html>
<html>
<head>
	<title>THE CRITIC'S PAGE</title>
	<!-- BOOTSTRAP -->

	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	{%load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	{%load static%}
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
	{%load static%}



</head>
<body>

	<div class="container-fluid">
		<div class="row">
		
			<div class="col-sm-2"></div><!-- Space -->


			<div class="col-sm-8" style="margin-top: 15%">
				<div class="jumbotron bg-danger text-light">
					{% block main%}


					{% endblock %}		
				</div>

			</div>

			<div class="col-sm-2"></div><!-- Space -->
		</div>
	</div>

	


</body>
</html>